### ISSUE TITLE
sisc_lab2020 project integration todo

### ISSUE THREAD

**Issue by broeder-j** [JuDFTteam/aiida-jutools#4]
Sum of the status and what needs to be done to integrate the tool:

- [ ] If datafiles are there querries should not be rerun
- [ ] overall to slow, reduce number of querries and reuse more information

D1:
- [x] Missing elements are not in element plot
- [ ] Coloring of element plot, could show how many different formulas
- [ ] Coloring of natoms and nstructures, could show how many different formulas
- [x] Other Information on the structure like spacegroup or volume (preprocess this)
- [x] If files for plots exists querries should not be rerun
- [x] Axis sclaes of some plots are fixed
- [ ] Processes show a table of all exit status, exit message and how often they occur and in relative terms, ggf plot this as some pie chart or bar chart
- [x] Axis and formatting of node versus user, combine these plots
- [x] Pie chart diagrams print total nodes in title
- [ ] Maybe display some more profile information and database sizes without pw at beginning if possible.
- [ ] Add further markup and explaination to the individual statistics

D2:
- [x] Polish the plot
- [ ] Can one include into a simple html file or app with datafile the switch on what is plotted
- [x]  Make more userfriendly. i.e drop down to select workflow, output node and then in the plot what can be shown

For integration:
- [ ] generalize bokeh plots and integrate into masci_tools
- [ ] Only leave data collections and processing methods here in aiida_jutools, together with the notebooks and resulting app

**Comment by Tanzp01** [comment]
Hi Jens,

I have a question regarding "Coloring of element plot, could show how many different formulas", "Coloring of natoms and nstructures, could show how many different formulas" of D1. Do you mean I should use different colors to represent number of different formulas? Or I should change the colors and also show number of different formulas?

Thanks if you could answer me.

**Comment by Tanzp01** [comment]
Hi Jens,
Another question regarding the process part, "how often they occur and in relative terms". Should I print a counted hierarchy of all the exit_status? Otherwise I didn't find any information about how often they occur. 
Thanks,
Zhipeng

**Comment by broeder-j** [comment]
Wow. I did not expect you to work on this, but thanks! I wrote this more as a note to myself/us what we should do while we integrate it, Which I will do once the scilab project is done/frozen.

now to your questions: 

1. Coloring of element plot. At the status of the run, the color had basicly no meaning. So the idea was to color how many different formulas there are. For this you first have to define the color bar and then apply the color bar to an array with this information.

2. See https://aiida-fleur.readthedocs.io/en/v1.1.3/user_guide/hints/exit_codes.html?highlight=exit%20codes#exit-codes
A sorted table either by occurance or exit code number would both be fine. If this does not tell much, a bar or piechart. total numbers have the problem they do not tell you much, usuful are usually both, total and with respect to the total number of processes of that type.
